repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2  
    hooks:
      - id: black
  
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    - id: autoflake
      args: [--remove-all-unused-imports, --in-place]